# Generated by Django 4.2.6 on 2023-11-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_costumer',
            new_name='is_customer',
        ),
    ]
